name: Publish release to npm
on:
  # For nightly releases
  schedule:
    - cron: '27 23 * * *' # at 23:27 every day
  # For manual releases
  workflow_dispatch:
    inputs:
      release-type:
        description: Type of release to publish.
        type: choice
        options:
          - stable
          - nightly
          - beta
          - rc
        default: stable
      version:
        description: Specific version to publish (usually inferred from x.y-stable branch name).
        type: string
        required: false
        default: ''
      dry-run:
        description: Whether to perform a dry run of the publish.
        type: boolean
        default: true

jobs:
  npm-build:
    if: github.repository == 'software-mansion/react-native-enriched-markdown'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write # for OIDC

    concurrency:
      group: publish-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Check out
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      - name: Publish manual release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: software-mansion/npm-package-publish@264013301cc21350186b190f1f6dd10ae4c8ee04 # 1.0.0
        with:
          package-name: 'react-native-enriched-markdown'
          package-json-path: 'packages/react-native-enriched-markdown/package.json'
          install-dependencies-command: 'YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install'
          release-type: ${{ inputs.release-type }}
          version: ${{ inputs.version }}
          dry-run: ${{ inputs.dry-run }}

      - name: Publish automatic nightly release
        if: ${{ github.event_name == 'schedule' }}
        uses: software-mansion/npm-package-publish@264013301cc21350186b190f1f6dd10ae4c8ee04 # 1.0.0
        with:
          package-name: 'react-native-enriched-markdown'
          package-json-path: 'packages/react-native-enriched-markdown/package.json'
          install-dependencies-command: 'YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install'
          release-type: 'nightly'
          dry-run: false
